version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: renthorpa_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: renthorpa_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: renthorpa_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: renthorpa_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: renthorpa_db
      DB_DIALECT: mysql
    depends_on:
      - db

  client:
    build: ./client
    container_name: renthorpa_client
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
